endpoints:
 - name: Example
   url: "https://example.org"
   interval: 1m
   conditions:
    - "[STATUS] == 200"
    - "[BODY].status == OK"
    
 - name: DNS Resolution
   group: DNS
   url: "8.8.8.8"
   dns:
      query-name: "gatus-rowaida.co.uk"
      query-type: "A"
   conditions:
      - "[DNS_RCODE] == NOERROR"

 - name: GitHub API
   group: External
   url: "https://api.github.com"
   conditions:
    - "[STATUS] == 200"
    - "[BODY].current_user_url == https://api.github.com/user"


 - name: TLS Certificate Check
   group: Security
   url: "https://gatus-rowaida.co.uk"
   interval: 6h
   conditions:
    - "[CERTIFICATE_EXPIRATION] > 720h"


 - name: Cloudflare ICMP
   group: Network
   url: "icmp://1.1.1.1"
   interval: 1m
   conditions:
    - "[CONNECTED] == true"
