endpoints:

 - name: My Website
   url: https://tm.gatus-rowaida.co.uk
   interval: 30s
   conditions:
     - "[STATUS] == 200"
    
 - name: DNS Resolution
   group: DNS
   url: "8.8.8.8"
   dns:
      query-name: "gatus-rowaida.co.uk"
      query-type: "A"
   conditions:
      - "[DNS_RCODE] == NOERROR"

 - name: GitHub API
   group: External
   interval: 30s
   url: "https://api.github.com"
   conditions:
    - "[STATUS] == 200"

 - name: TLS Certificate Check
   group: Security
   url: "https://tm.gatus-rowaida.co.uk"
   interval: 30s
   conditions:
    - "[CERTIFICATE_EXPIRATION] > 720h"


