name: Docker build & push to ECR

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "push" to build and push the Docker image'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region "${{ env.AWS_REGION }}" \
            | docker login --username AWS --password-stdin \
            "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"

       
      - name: Build image (latest + sha)
        run: |
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY_NAME }}"
          docker build \
           -f ./gatus-app/Dockerfile \
           -t "${IMAGE_URI}:latest" \
           -t "${IMAGE_URI}:${{ github.sha }}" \
           ./gatus-app

    
      - name: Install Trivy (robust)
        run: |
          set -euo pipefail
          TRIVY_VERSION="0.65.0"
          FILE="trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz"
          URL="https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/${FILE}"

          echo "Downloading $URL"
          curl -L --fail --retry 5 --retry-delay 2 -o "$FILE" "$URL"
          echo "File size:"
          ls -lh "$FILE"

          cho "Extracting..."
          tar -xzf "$FILE"

          echo "Installing..."
          sudo install -m 0755 trivy /usr/local/bin/trivy
 
          echo "Trivy version:"

          trivy --version

      - name: Trivy scan (table)
        run: |
         IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY_NAME }}"
         trivy image --format table "${IMAGE_URI}:${{ github.sha }}"



      - name: Push image (latest + sha)
        run: |
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY_NAME }}"
          docker push "${IMAGE_URI}:latest"
          docker push "${IMAGE_URI}:${{ github.sha }}"
